export const classes = [
  {
    name: 'CS-PRACT41',
    room: 'Rm 301',
    schedule: '11965',
    days: 'MWF',
    time: '8:00 - 9:30 AM',
    units: 3,
    students: 10,
    instructorEmail: 'maria.santos@example.com',
  },
  {
    name: 'CS-FRELEAN',
    room: 'Rm 402',
    schedule: '11973',
    days: 'TTH',
    time: '9:00 - 10:30 AM',
    units: 3,
    students: 8,
    instructorEmail: 'juan.delacruz@example.com',
  },
  {
    name: 'CS-OPSYS41',
    room: 'Rm 305',
    schedule: '11981',
    days: 'MWF',
    time: '10:00 - 11:30 AM',
    units: 3,
    students: 6,
    instructorEmail: 'ricardo.gomez@example.com',
  },
  {
    name: 'CS-THESIS41',
    room: 'Rm 501',
    schedule: '12005',
    days: 'TTH',
    time: '2:30 - 4:00 PM',
    units: 3,
    students: 6,
    instructorEmail: 'elena.rodriguez@example.com',
  },
  {
    name: 'CC-COMPROG11',
    room: '538',
    schedule: '11965',
    days: 'MWF',
    time: '8:00 - 9:30 AM',
    units: 3,
    students: 15,
    instructorEmail: 'maria.santos@example.com',
  },
];
