export const classes = [
  {
    code: 'CS-THESIS42',
    title: 'Thesis 2',
    room: 'Rm 502',
    schedule: '12013',
    days: 'TTH',
    time: '4:00 - 5:30 PM',
    units: 3,
    students: 6,
    instructorEmail: 'elena.rodriguez@example.com',
  },
  {
    code: 'CC-PROFIS10',
    title: 'Professional Issues in Computing',
    room: 'Rm 302',
    schedule: '11995',
    days: 'MWF',
    time: '1:00 - 2:30 PM',
    units: 3,
    students: 12,
    instructorEmail: 'maria.santos@example.com',
  },
  {
    code: 'ELEMSYS',
    title: 'Embedded Systems & IoT',
    room: 'Lab 1',
    schedule: '12021',
    days: 'MWF',
    time: '2:30 - 4:00 PM',
    units: 3,
    students: 8,
    instructorEmail: 'ricardo.gomez@example.com',
  },
  {
    code: 'ELDNET1',
    title: '.NET Programming Module 1',
    room: 'Lab 2',
    schedule: '12035',
    days: 'TTH',
    time: '9:00 - 10:30 AM',
    units: 3,
    students: 10,
    instructorEmail: 'juan.delacruz@example.com',
  },
  {
    code: 'CS-THESIS41',
    title: 'Thesis 1',
    room: 'Rm 501',
    schedule: '12005',
    days: 'TTH',
    time: '2:30 - 4:00 PM',
    units: 3,
    students: 6,
    instructorEmail: 'elena.rodriguez@example.com',
  },
  {
    code: 'CS-OPSYS41',
    title: 'Operating Systems',
    room: 'Rm 305',
    schedule: '11981',
    days: 'MWF',
    time: '10:00 - 11:30 AM',
    units: 3,
    students: 6,
    instructorEmail: 'ricardo.gomez@example.com',
  },
  {
    code: 'CS-PRACT41',
    title: 'Practicum',
    room: 'Rm 301',
    schedule: '11965',
    days: 'MWF',
    time: '8:00 - 9:30 AM',
    units: 3,
    students: 10,
    instructorEmail: 'maria.santos@example.com',
  },
  {
    code: 'CS-FRELEAN',
    title: 'Lean Startup Methodology',
    room: 'Rm 402',
    schedule: '11973',
    days: 'M-SUN',
    time: '24/7',
    units: 3,
    students: 8,
    instructorEmail: 'juan.delacruz@example.com',
  },
];
