export const students = [
  // BSCS - Section A
  {
    studentNumber: '22655001',
    firstName: 'John',
    lastName: 'Dela Cruz',
    email: 'john.delacruz@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    course: 'BSCS',
    year: 3,
    section: 'A',
    classes: ['CS-PRACT41', 'CS-THESIS41', 'CS-OPSYS41'],
  },
  {
    studentNumber: '22655002',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria.garcia@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    course: 'BSCS',
    year: 3,
    section: 'A',
    classes: ['CS-PRACT41', 'CS-THESIS41', 'CS-OPSYS41'],
  },
  {
    studentNumber: '22655003',
    firstName: 'Pedro',
    lastName: 'Reyes',
    email: 'pedro.reyes@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pedro',
    course: 'BSCS',
    year: 3,
    section: 'A',
    classes: ['CS-PRACT41', 'CS-THESIS41', 'CS-OPSYS41'],
  },
  // BSCS - Section B
  {
    studentNumber: '22655004',
    firstName: 'Ana',
    lastName: 'Santos',
    email: 'ana.santos@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
    course: 'BSCS',
    year: 3,
    section: 'B',
    classes: ['CS-PRACT41', 'CS-THESIS41', 'CS-OPSYS41'],
  },
  {
    studentNumber: '22655005',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'james.wilson@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    course: 'BSCS',
    year: 3,
    section: 'B',
    classes: ['CS-PRACT41', 'CS-THESIS41', 'CS-OPSYS41'],
  },
  // BSIT - Section A
  {
    studentNumber: '22655006',
    firstName: 'Jose',
    lastName: 'Mendoza',
    email: 'jose.mendoza@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jose',
    course: 'BSIT',
    year: 2,
    section: 'A',
    classes: ['CS-FRELEAN', 'CC-COMPROG11'],
  },
  {
    studentNumber: '22655007',
    firstName: 'Sophia',
    lastName: 'Turner',
    email: 'sophia.turner@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia',
    course: 'BSIT',
    year: 2,
    section: 'A',
    classes: ['CS-FRELEAN', 'CC-COMPROG11'],
  },
  // Irregular Students (Mixed Section/Classes)
  {
    studentNumber: '22655008',
    firstName: 'Oliver',
    lastName: 'Wilson',
    email: 'oliver.wilson@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Oliver',
    course: 'BSCS',
    year: 3,
    section: 'IRR',
    classes: ['CS-PRACT41', 'CC-COMPROG11'],
  },
  {
    studentNumber: '22655009',
    firstName: 'Isabella',
    lastName: 'Lopez',
    email: 'isabella.lopez@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella',
    course: 'BSIT',
    year: 4,
    section: 'IRR',
    classes: ['CS-PRACT41', 'CS-THESIS41'],
  },
  {
    studentNumber: '22655010',
    firstName: 'Liam',
    lastName: 'Martinez',
    email: 'liam.martinez@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Liam',
    course: 'BSHM',
    year: 1,
    section: 'A',
    classes: ['CC-COMPROG11'],
  }
];
