export const students = [
  {
    firstName: 'John',
    lastName: 'Dela Cruz',
    email: 'john.delacruz@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    course: 'BSCS',
    year: 4,
    section: 'A',
    classes: ['CS-PRACT41', 'CS-THESIS41', 'CS-OPSYS41'],
  },
  {
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria.garcia@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    course: 'BSCS',
    year: 4,
    section: 'A',
    classes: ['CS-PRACT41', 'CS-THESIS41', 'CS-OPSYS41'],
  },
  {
    firstName: 'Pedro',
    lastName: 'Reyes',
    email: 'pedro.reyes@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pedro',
    course: 'BSCS',
    year: 4,
    section: 'A',
    classes: ['CS-PRACT41', 'CS-THESIS41', 'CS-OPSYS41'],
  },
  {
    firstName: 'Ana',
    lastName: 'Santos',
    email: 'ana.santos@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
    course: 'BSCS',
    year: 4,
    section: 'A',
    classes: ['CS-PRACT41', 'CS-THESIS41', 'CS-OPSYS41'],
  },
  {
    firstName: 'Jose',
    lastName: 'Mendoza',
    email: 'jose.mendoza@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jose',
    course: 'BSIT',
    year: 4,
    section: 'B',
    classes: ['CS-PRACT41', 'CS-FRELEAN', 'CC-COMPROG11'],
  },
  {
    firstName: 'Sophia',
    lastName: 'Turner',
    email: 'sophia.turner@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia',
    course: 'BSIT',
    year: 4,
    section: 'B',
    classes: ['CS-PRACT41', 'CS-FRELEAN', 'CC-COMPROG11'],
  },
  {
    firstName: 'Oliver',
    lastName: 'Wilson',
    email: 'oliver.wilson@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Oliver',
    course: 'BSIT',
    year: 4,
    section: 'B',
    classes: ['CS-PRACT41', 'CS-FRELEAN', 'CC-COMPROG11'],
  },
  {
    firstName: 'Isabella',
    lastName: 'Garcia',
    email: 'isabella.garcia@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella',
    course: 'BSIS',
    year: 3,
    section: 'C',
    classes: ['CS-FRELEAN', 'CC-COMPROG11'],
  },
  {
    firstName: 'Liam',
    lastName: 'Martinez',
    email: 'liam.martinez@student.example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Liam',
    course: 'BSIS',
    year: 3,
    section: 'C',
    classes: ['CS-FRELEAN', 'CC-COMPROG11'],
  },
];
